version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "2222:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/html:/usr/share/nginx/html
      - ./data/static:/var/www/html/static_files