apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: {{ .Values.app }}
  ports:
    - port: {{ .Values.application_port }}
      targetPort: {{ .Values.application_port }}
      nodePort: {{ .Values.nodeport }}
